### PR TITLE
Add VPClient

### PR DESCRIPTION
**Pull request by chippytech**
We have added VPClient to MOFH API Docs

### CODE REVIEW

**Comment by Wallvon** [comment]
Hi, thanks for your pull request. There are a few fixes that would have to be made before this can be merged:

- Make it like the other wrappers that are listed, so that would be `* [VPClient](https://github.com/GenerateApps/VPClient) (PHP)` and move it to the existing list.
- Add a changelog entry.

I will be happy to make these changes when I find the time for it, but if you feel this is urgent, you may also edit your PR.

**Comment by 4yx** [comment]
Not sure about this personally, as VPClient is a VistaPanel API client, and this project is currently dedicated to the MOFH API only. Perhaps it could be expanded to include the vP endpoints? Would that be better for a separate project? What are your thoughts?

**Comment by Wallvon** [comment]
Ah, I got the purpose of the project wrong then - sorry about this.

We could make a separate category for this, dedicate a page to MOFH or VistaPanel API clients, or do something else. I don't know what would be the way to go in this case, but I don't mind also covering vPanel here since it is closely related anyways.

8 Jun 2023 00:44:49 Anyx ***@***.***>:

**Comment by greenreader9** [comment]
I don't think he is going to come back and fix this, vote to close.

**Pull request closed without merging**
