### PR TITLE
Update formatting in callbacks.mdx

### PR DESCRIPTION
**Pull request by greenreader9**
Changes made:

In reference to #36 and #22 :
 - Removed the "Account Suspension" heading
 -  So the story behind that one is I just copied the <callout> code, and got the heading with it as well. I never noticed the extra line, and neither did anyone else for nearly an entire year. We are all very observant people

Updated formatting:
- On smaller screens, the bullet points take up too much vertical space
- It just looks better (To me anyways) with it all one one line

### CODE REVIEW

**Comment by greenreader9** [comment]
Also - Is a change request entry needed for aesthetic changes?

**Comment by Wallvon** [comment]
> Also - Is a change request entry needed for aesthetic changes?

What do you mean by this?

**Comment by greenreader9** [comment]
Does the changelog need to be updated for changes that are _not_ adding / removing anything major (Like this pull) for the project?

**Comment by Wallvon** [comment]
I'll add the changes to the changelog to this pull request since I also caught an issue on the callbacks page

**Pull request merged**
